apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-event-test-producer
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-event-test-producer-secrets
    - configmap: loginservice-idporten
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-event-test-producer/isAlive
    initialDelay: 5
  readiness:
    path: /tms-event-test-producer/isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  ingresses:
    - "https://www.intern.nav.no/tms-event-test-producer"
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 64Mi
  kafka:
    pool: nav-prod

