apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-event-test-producer
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-event-test-producer-secrets
    - configmap: loginservice-idporten
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-event-test-producer/isAlive
    initialDelay: 5
  readiness:
    path: /tms-event-test-producer/isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dittnav-event-handler
          namespace: personbruker
  ingresses:
    - "https://person.dev.nav.no/tms-event-test-producer"
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  kafka:
    pool: nav-dev
