apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-event-test-producer
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - configmap: loginservice-idporten
  image: {{version}}
  port: 8080
  liveness:
    path: /tms-event-test-producer/isAlive
    initialDelay: 5
  readiness:
    path: /tms-event-test-producer/isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  idporten:
    enabled: true
    postLogoutRedirectURIs:
      - "https://www.dev.nav.no"
    sidecar:
      enabled: true
      level: Level3
  ingresses:
    - "https://www.intern.dev.nav.no/tms-event-test-producer"
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 128Mi
  kafka:
    pool: nav-dev
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: www.intern.dev.nav.no
    - name: ENABLE_API
      value: "true"
    - name: EVENT_HANDLER_URL
      value: https://dittnav-event-handler.dev.intern.nav.no
    - name: EVENTHANDLER_CLIENT_ID
      value: dev-gcp:min-side:dittnav-event-handler
    - name: OPEN_INPUT_BESKJED_TOPIC
      value: min-side.aapen-brukernotifikasjon-beskjed-v1
    - name: OPEN_INPUT_DONE_TOPIC
      value: min-side.aapen-brukernotifikasjon-done-v1
    - name: OPEN_INPUT_INNBOKS_TOPIC
      value: min-side.aapen-brukernotifikasjon-innboks-v1
    - name: OPEN_INPUT_OPPGAVE_TOPIC
      value: min-side.aapen-brukernotifikasjon-oppgave-v1
    - name: OPEN_INPUT_STATUSOPPDATERING_TOPIC
      value: min-side.aapen-brukernotifikasjon-statusoppdatering-v1
    - name: UTKAST_TOPIC_NAME
      value: min-side.aapen-utkast-v1


